name: my_portfolio
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_theme_switcher: ^2.0.10
  google_fonts: ^6.3.0
  flutter_riverpod: ^2.6.1
  responsive_framework: ^1.5.1
  url_launcher: ^6.3.2

  flutter_web_plugins: 
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/social/
    - assets/images/technology/
    - assets/images/

